services:
  - type: web
    name: academiaconnect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ucu_chapters.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ucu_chapters.settings
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0