services:
  - type: web
    name: academiaconnect
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn --chdir ucu_chapters ucu_chapters.wsgi:application --bind=0.0.0.0:$PORT --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ucu_chapters.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: WEB_CONCURRENCY
        value: 4