services:
  - type: web
    name: academiaconnect
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: cd ucu_chapters && gunicorn wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ucu_chapters.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000