services:
  - type: web
    name: academiaconnect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ucu_chapters.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ucu_chapters.settings
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000