# Generated by Django 4.2 on 2025-04-04 16:17

import chapters.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Registration number must be in format UCU/YYYY/XXX', regex='^UCU/\\d{4}/\\d{3}$'), chapters.models.validate_registration_number]),
        ),
    ]
